name: psNakivo

on:
  push

permissions:
  contents: read

jobs:
    # The job that will use the container image you just pushed to ghcr.io
    Test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/we-mi/nakivo-multitenant-full:latest
            credentials:
               username: we-mi
               password: ${{ secrets.GHCR_TOKEN }}
        steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Perform the generic pester test
          shell: pwsh
          run: |
            Invoke-Pester -Output Detailed tests\Generic.Test.ps1 -PassThru