name: psNakivo

on:
  push

permissions:
  contents: read

jobs:
    # The job that will use the container image you just pushed to ghcr.io
    Test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/we-mi/nakivo-multitenant-full:latest
            credentials:
               username: we-mi
               password: ${{ secrets.GHCR_TOKEN }}
        steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Install Pester
          shell: pwsh
          run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module Pester -Confirm:$false -Force
        - name: Run pester tests in ./tests
          shell: pwsh
          run: |
            Get-ChildItem -Path test -Filter "*.Test.ps1" | ForEach-Object {
                Write-Host "Run test: $($_.Name)"
                Invoke-Pester -Output Detailed $_.FullName -PassThru
            }