name: psNakivo

on:
  push

permissions:
  contents: read

jobs:
    # The job that will use the container image you just pushed to ghcr.io
    Test:
        runs-on: ubuntu-latest
        container:
            image: ghcr.io/we-mi/nakivo-multitenant-full:latest
            credentials:
               username: we-mi
               password: ${{ secrets.GHCR_TOKEN }}
        steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Make sure the nakivo service is started
          shell: sh
          run: /etc/init.d/nkv-dirsvc start
        - name: Install Pester
          shell: pwsh
          run: |
            Set-PSRepository PSGallery -InstallationPolicy Trusted
            Install-Module Pester -Confirm:$false -Force
        - name: Run pester tests in ./tests
          shell: pwsh
          run: .\runTests.ps1 -Server localhost -Username admin -Password $null